# Generated by Django 4.2.7 on 2023-11-29 19:31

import app.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Leki',
            },
        ),
        migrations.CreateModel(
            name='Lekarz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telefon', models.CharField(max_length=14, validators=[django.core.validators.MinLengthValidator(9)])),
            ],
            options={
                'verbose_name_plural': 'Lekarze',
            },
        ),
        migrations.CreateModel(
            name='Pacjet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pesel', models.CharField(max_length=11, unique=True)),
                ('imie', models.CharField(max_length=30)),
                ('nazwisko', models.CharField(max_length=50)),
                ('telefon', models.CharField(max_length=14, validators=[django.core.validators.MinLengthValidator(9)])),
                ('email', models.CharField(max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': 'Pacjeci',
            },
        ),
        migrations.CreateModel(
            name='Pielegniarka',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uprawnienia', models.CharField(choices=[('I Stopien', 'I Stopien'), ('II Stopien', 'II Stopien')], default='I', max_length=15)),
                ('telefon', models.CharField(max_length=14, validators=[django.core.validators.MinLengthValidator(9)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Pielegniarki',
            },
        ),
        migrations.CreateModel(
            name='Specjalizacje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Specjalizacje',
            },
        ),
        migrations.CreateModel(
            name='StatusWizyty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Statusy wizyt',
            },
        ),
        migrations.CreateModel(
            name='Wizyta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cel_wizyty', models.TextField(help_text='Opisz w jakim celu pacjent chce przyjsc')),
                ('data', models.DateTimeField(validators=[app.models.spr_data])),
                ('lekarz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.lekarz')),
                ('pacjent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.pacjet')),
                ('pielegniarka', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.pielegniarka')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.statuswizyty')),
            ],
            options={
                'verbose_name_plural': 'Wizyty',
            },
        ),
        migrations.CreateModel(
            name='Sekretarka',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telefon', models.CharField(max_length=14, validators=[django.core.validators.MinLengthValidator(9)])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Sekretarki',
            },
        ),
        migrations.CreateModel(
            name='Recepta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('leki', models.ManyToManyField(to='app.lek')),
                ('wizyta', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='recepta', to='app.wizyta')),
            ],
            options={
                'verbose_name_plural': 'Recepty',
            },
        ),
        migrations.CreateModel(
            name='NotatkaWizyty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('opis', models.TextField(help_text='Opis wizyty, ustalenia, dalsze kroki')),
                ('wizyta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opis_wizyty', to='app.wizyta')),
            ],
            options={
                'verbose_name_plural': 'Notatki do wizyt',
            },
        ),
        migrations.AddField(
            model_name='lekarz',
            name='specjalizacja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.specjalizacje'),
        ),
        migrations.AddField(
            model_name='lekarz',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
